# -*- coding: utf-8 -*-
"""Image_compress.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XgbrRSDkdc6f01UYKbe9Mxt0owBTT0ob
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

img=plt.imread("/content/tiger.jpg")
plt.imshow(img)
plt.axis("off")
plt.show()

print(img.shape)

w,h,d=img.shape
image_array=img.reshape(w*h,d)
#normalize image
image_array=image_array/255

from sklearn.utils import shuffle

#taking array sub sample:
image_sample=shuffle(image_array,random_state=1)[:1000]
image_sample.size

kmean=KMeans(n_clusters=7,random_state=1)
kmean.fit(image_sample)

labels=kmean.predict(image_array)
labels

print(kmean.cluster_centers_)
c=kmean.cluster_centers_

def recreate_image(c,labels,w,h,d):
  image=np.zeros((w,h,d))
  label_idx=0
  for i in range(w):
    for j in range(h):
      image[i][j]=c[labels[label_idx]]
      label_idx+=1

  return image

new_image=recreate_image(c,labels,w,h,d)

plt.figure(1)
plt.imshow(img)
plt.title("original Image")
plt.axis("off")
plt.show()
plt.figure(2)
plt.imshow(new_image)
plt.title("Complressed Image")
plt.axis("off")
plt.show()

